### PR TITLE
Phantomjs

### PR DESCRIPTION
**Pull request by cesy**
This fixes the merge conflicts. I'm now testing it out locally.

### CODE REVIEW

**Comment by pozorvlak** [comment]
What's the status of this? Do we need to re-open it against growstuff/growstuff?

**Comment by cesy** [comment]
I think so - we'll need to combine your changes and mine and do a clean PR.

**Comment by pozorvlak** [comment]
OK, cool. I'd like to get Release 10 out in the next few days - shall we
aim to get this into Release 11?​

**Comment by cesy** [comment]
Yeah, makes sense.

**Pull request closed without merging**
